apiVersion: v1
clusters:
  - cluster:
      certificate-authority: /Users/Sattvik/.minikube/ca.crt
      extensions:
        - extension:
            last-update: Thu, 16 May 2024 13:13:43 EDT
            provider: minikube.sigs.k8s.io
            version: v1.33.1
          name: cluster_info
      server: https://127.0.0.1:50004
    name: minikube
  - cluster:
      certificate-authority: /Users/Sattvik/.minikube/ca.crt
      extensions:
        - extension:
            last-update: Tue, 14 May 2024 17:37:12 EDT
            provider: minikube.sigs.k8s.io
            version: v1.33.1
          name: cluster_info
      server: https://127.0.0.1:52809
    name: multinode-demo
contexts:
  - context:
      cluster: minikube
      extensions:
        - extension:
            last-update: Thu, 16 May 2024 13:13:43 EDT
            provider: minikube.sigs.k8s.io
            version: v1.33.1
          name: context_info
      namespace: default
      user: minikube
    name: minikube
  - context:
      cluster: multinode-demo
      extensions:
        - extension:
            last-update: Tue, 14 May 2024 17:37:12 EDT
            provider: minikube.sigs.k8s.io
            version: v1.33.1
          name: context_info
      namespace: default
      user: multinode-demo
    name: multinode-demo
current-context: minikube
kind: Config
preferences: {}
users:
  - name: minikube
    user:
      client-certificate: /Users/Sattvik/.minikube/profiles/minikube/client.crt
      client-key: /Users/Sattvik/.minikube/profiles/minikube/client.key
  - name: multinode-demo
    user:
      client-certificate: /Users/Sattvik/.minikube/profiles/multinode-demo/client.crt
      client-key: /Users/Sattvik/.minikube/profiles/multinode-demo/client.key
