apiVersion: batch.example.com/v1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: audit-http
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-sample
  namespace: default
spec:
  url: "http://example.com"
  expectedStatus: 200
  schedule: "* * * * *"
