apiVersion: batch.example.com/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: audit-http
    app.kubernetes.io/managed-by: kustomize
  name: cronjob-sample
spec:
  # TODO(user): Add fields here
