apiVersion: batch.github.com/v1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: audit-http
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan-sample
# spec:
#   # TODO(user): Add fields here
