apiVersion: batch.example.com/v1
kind: ClusterScan
metadata:
  name: clusterscan-sample
  namespace: default
spec:
  httpChecks:
    - podName: pod1
      namespace: default
      url: "http://pod1.default.svc.cluster.local"
    - podName: pod2
      namespace: default
      url: "http://pod2.default.svc.cluster.local"
    - podName: pod3
      namespace: default
      url: "http://pod3.default.svc.cluster.local"
  schedule: "* * * * *"
